---
- name: POST VAGRANT UP PROVISIONING
  hosts: n9k2
  gather_facts: no

  vars:
    ssh:
      host: '{{ ansible_ssh_host }}'
      username: 'admin'
      password: 'admin'
      transport: cli

  tasks:
    - name: configure hostname and domain-name
      nxos_system:
        provider: '{{ ssh }}'
        hostname: '{{ inventory_hostname }}'
        domain_name: vagrantlab.local

    - name: ensure nxapi is enabled
      nxos_feature:
        feature: nxapi
        state: enabled
        provider: '{{ ssh }}'

    - name: ensure lldp is enabled
      nxos_feature:
        feature: lldp
        state: enabled
        provider: '{{ ssh }}'

    - name: Create SNMPv3 user
      nxos_snmp_user:
        provider: '{{ ssh }}'
        user: wavefront
        group: network-operator
        authentication: md5
        pwd: cisco123
        state: present
        privacy: cisco123
        encrypt: True

    - name: Enable SNMP Traps
      nxos_snmp_traps:
        group: all
        state: enabled

    - name: Setup SNMP Host
      nxos_snmp_host: 
        snmp_host: 10.10.0.144
        community: wavefront
        state: present
        snmp_type: trap
        provider: '{{ ssh }}'
        v3: priv
        upd: 162
        version: v3
        vrf: management

    - name: configure no password strength check
      nxos_command: 
        commands: 
          - configure terminal
          - no password strength-check
        wait_for:
          - result[0] contains no

    - name: configure globalEnforcePriv 
      nxos_command:
        commands: 
          - configure terminal
          - snmp-server globalEnforcePriv 
        wait_for:
          - result[0] contains snmp


